server:
  port: 8080

debug: false

logging:
 level:
  #Root log output at warn level
  application: info

client:
  registration:
    name: app

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          app:
            provider: appprovider
            client-id: 
            client-secret: 
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            scope: hello
          user:
            provider: userprovider
            client-id: 
            client-secret: 
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: hello
            client-authentication-method: post
        provider:
          appprovider:
            token-uri: https://api.service.hmrc.gov.uk/oauth/token
          userprovider:
            token-uri: https://api.service.hmrc.gov.uk/oauth/token
            authorization-uri: https://api.service.hmrc.gov.uk/oauth/authorize